global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'erigon'
    static_configs:
      - targets: ['erigon:6060']
        labels:
          instance: 'erigon-test'
